version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development} 
    container_name: nextjs-app
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    env_file:
      - docker.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    expose:
      - "80"
    env_file:
      - docker.env
    environment:
      - PGADMIN_SCRIPT_NAME=/pgadmin
    depends_on:
      - postgres
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx_logs:/var/log/nginx
    depends_on:
      - nextjs
      - pgadmin
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local
  next_data:
    driver: local
  nginx_logs:
    driver: local

networks:
  app-network:
    driver: bridge