version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development} 
    container_name: nextjs-app
    restart: always
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    env_file:
      - docker.env

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    env_file:
      - docker.env
    depends_on:
      - postgres
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
